name: student_registry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/nulogo.png
