// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvfke-OP9mY4-tsOAcT4eF-y4gi8sVuuU',
    appId: '1:708296893763:web:ce599e4f6a0d4a97f63bf6',
    messagingSenderId: '708296893763',
    projectId: 'flutterlabproj',
    authDomain: 'flutterlabproj.firebaseapp.com',
    storageBucket: 'flutterlabproj.firebasestorage.app',
    measurementId: 'G-R5WB4QRQYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfw3Kq8dbPMmROTMGkDM4gOC9N3NPK7qw',
    appId: '1:708296893763:android:3027cde264fcad24f63bf6',
    messagingSenderId: '708296893763',
    projectId: 'flutterlabproj',
    storageBucket: 'flutterlabproj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZfMR9uwpwgeLXMPbcccGATl-i7q8_FY',
    appId: '1:708296893763:ios:1fc4d5ebf0fa1cd7f63bf6',
    messagingSenderId: '708296893763',
    projectId: 'flutterlabproj',
    storageBucket: 'flutterlabproj.firebasestorage.app',
    iosBundleId: 'com.example.labFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADZfMR9uwpwgeLXMPbcccGATl-i7q8_FY',
    appId: '1:708296893763:ios:1fc4d5ebf0fa1cd7f63bf6',
    messagingSenderId: '708296893763',
    projectId: 'flutterlabproj',
    storageBucket: 'flutterlabproj.firebasestorage.app',
    iosBundleId: 'com.example.labFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvfke-OP9mY4-tsOAcT4eF-y4gi8sVuuU',
    appId: '1:708296893763:web:87319068d5ae28abf63bf6',
    messagingSenderId: '708296893763',
    projectId: 'flutterlabproj',
    authDomain: 'flutterlabproj.firebaseapp.com',
    storageBucket: 'flutterlabproj.firebasestorage.app',
    measurementId: 'G-VRJ60N2R9P',
  );
}
